#!/bin/bash
set -x
tomcat_version="apache-tomcat-11.0.2"
tomcat_url="https://dlcdn.apache.org/tomcat/tomcat-11/v11.0.2/bin/apache-tomcat-11.0.2.tar.gz"
#tomcat_tarfile="apache-tomcat-11.0.2.tar.gz"
#update required packages
sudo apt update
#install tomcat
echo "install tomcat"
wget $tomcat_url
if [ $? -eq 0 ]
then
echo "Extract tar file"
 tar -xvf $tomcat_version.tar.gz
echo "Tomcat 11.0.2 installed successfully"
else
        "Tomcat failed to install"
fi
